from sqlalchemy import Column, String, Boolean, BigInteger, Numeric, Date, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Proposal(Base):
    __tablename__ = "crm.proposal"

    id = Column(String(500), primary_key=True)
    ods_2_day__c = Column(Boolean)
    ods_2_day_max_quantity__c = Column(BigInteger)
    ods_3_day__c = Column(Boolean)
    ods_3_day_max_quantity__c = Column(BigInteger)
    ods_5_day__c = Column(Boolean)
    ods_5_day_max_quantity__c = Column(BigInteger)
    ods_account__c = Column(String(500))
    ods_accounting__c = Column(String(500))
    ods_additional_attributes_notes__c = Column(Text)
    ods_buyout__c = Column(Boolean)
    ods_consider_for_revenue_generation__c = Column(Boolean)
    ods_certified_mail__c = Column(Boolean)
    ods_commission_percent__c = Column(Numeric(20, 5))
    ods_complex_quote__c = Column(Boolean)
    ods_expected_end_date__c = Column(Date)
    ods_expected_start_date__c = Column(Date)
    ods_csm__c = Column(String(500))
    ods_customer_requirements__c = Column(Text)
    ods_data_composition__c = Column(Text)
    ods_data_composition_other__c = Column(Text)
    ods_delivery_to_post_office__c = Column(Boolean)
    ods_description__c = Column(Text)
    ods_distribution__c = Column(Text)
    ods_distribution_other__c = Column(Text)
    ods_due_date__c = Column(Date)
    ods_estimated_quote_value__c = Column(Numeric(20, 5))
    ods_estimation_leader__c = Column(String(500))
    ods_estimation_checklist__c = Column(String(500))
    ods_estimating_team_user__c = Column(String(500))
    ods_file_available_for_asset_creation__c = Column(Boolean)
    ods_first_class_mail__c = Column(Boolean)
    ods_fulfillment__c = Column(Text)
    ods_is_duplicate_proposal__c = Column(Boolean)
    ods_is_enddate_blank__c = Column(Boolean)
    cpq_it_required__c = Column(Boolean)
    ods_jira_number__c = Column(Text)
    ods_jira_number_formula__c = Column(Text)
    ods_legacy_proposal_id__c = Column(String(500))
    ods_maximum_qty__c = Column(Numeric(15, 5))
    ods_next_day__c = Column(Boolean)
    ods_next_day_max_quantity__c = Column(BigInteger)
    ods_opportunity__c = Column(String(500))
    ods_packaging__c = Column(String(500))
    ods_packaging_other__c = Column(String(500))
    ods_pending_activation__c = Column(Boolean)
    ods_plant__c = Column(String(500))
    ods_po_box_collection__c = Column(Boolean)
    ods_presented_date__c = Column(Date)
    ods_previous_legacy_proposal_id__c = Column(String(500))
    ods_previous_proposal_id__c = Column(String(500))
    ods_pricing_notes__c = Column(Text)
    ods_primary_contact__c = Column(String(500))
    ods_project_owner_project_contact__c = Column(String(500))
    ods_proposal_generated_date__c = Column(Date)
    ods_proposal_id__c = Column(String(500))
    ods_proposal_name__c = Column(String(500))
    ods_proposal_primary__c = Column(Boolean)
    ods_quote_stage__c = Column(String(500))
    ods_ready_for_estimation_date__c = Column(Date)
    ods_ready_for_sales_date__c = Column(Date)
    ods_sales_rep__c = Column(String(500))
    ods_same_day__c = Column(Boolean)
    ods_same_day_max_quantity__c = Column(BigInteger)
    ods_schedule__c = Column(Text)
    ods_scope_of_work__c = Column(Text)
    ods_secure_destruction__c = Column(Boolean)
    ods_standard_mail__c = Column(Boolean)
    ods_submitted_by__c = Column(String(500))
    ods_t_c__c = Column(Text)
    ods_total_net_price__c = Column(Numeric(15, 5))
    ods_valid_until_date__c = Column(Date)
    proposalid = Column(String(500))

# Grant permissions would be handled at the database level, not in SQLAlchemy code
